config/routes.rb
Rails.application.routes.draw do  
  resources :tasks do
    member do
      get 'complete'
      get 'reset'
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

	validates :name, :due_date, presence: true
	validates :completed, inclusion: [true, false]
		
	after_initialize :default_values
	def default_values()
		self.due_date ||= 'Date.now'
		self.completed ||= false
	end

	def complete!()
    	self.completed = true
  	end

  	def reset!()
  		self.completed = false
  	end

  	def complete?()
  		if self.completed == true
  			return true
  		end
  	end

  	def incomplete?()
  		if self.completed == false
  			return true
  		end 
  	end

  	def notes_preview()
  		if self.notes == nil
  			return nil
  		else
  			return :notes[0, 39]
  		end
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  def index
  	if not session[:data]
      session[:data] = []
    end

  	if params[:show_completed]
		session[:data].push params[:show_completed]
	end
  	if session[:data].last == "1"
	    @tasks = Task.all
	else
		@tasks = Task.where("completed = ?", false)
	end
  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
    	#successful save
      redirect_to @task
    else
      render "new"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render "edit"
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:name, :notes, :due_date, :completed)
  end

  def complete
    @task = Task.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to tasks_path
  end

  def reset
	@task = Task.find(params[:id])
	@task.completed = false
	@task.save
    redirect_to tasks_path
  end


  def foo
	if not session[:data]
  		session[:data] = []
	end

	if params[:remember]
  		session[:data].push params[:remember]
	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FtwTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>

  <%= t.label      :name %>
  <%= t.text_field :name %>

  <%= t.label      :notes %>
  <%= t.text_field :notes %>

  <%= t.label       :due_date %>
  <%= t.date_select :due_date %>

  <%= t.label     :completed %>
  <%= t.check_box :completed %>

  <%= t.submit :submit %>

<% end %>

app/views/tasks/_task_row.html.erb
<% @tasks.each do |t| %>
			<tr>
			  <td><%= t.name %></td>
			  <td><%= t.notes %></td>
			  <td><%= t.due_date.strftime("%m-%d-%Y") %></td>
			  <td><%= t.completed %></td>
			  <td><%= link_to 'Show', t %></td>
			  <td><%= link_to 'Edit', edit_task_path(t) %></td>
			  <% if t.completed == false %>
			  	<td><%= link_to 'Complete', complete_task_path(t) %></td>
			  <% else %>
			  	<td><%= link_to 'Reset', reset_task_path(t) %></td>
			  <% end %>
			  <td><%= link_to 'Delete', t, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>

app/views/tasks/_tasks_table.html.erb
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Notes</th>
			<th>Due Date</th>
			<th>Completed?</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<%= render 'task_row' %>
	</tbody>
</table>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<% if @task.errors.any? %>
There were some errors!
<ul>
  <% @task.errors.full_messages.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<%= render 'form' %>

<hr />


<ul>
  <li><%= link_to "Back to details", @task %></li>
  <li><%= link_to "Back to index", tasks_path %></li>
</ul>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= render 'tasks_table' %>

<hr />

<ul>
  <li><%= link_to 'New task', new_task_path %></li>
  <% if session[:data].last  == "1" %>
  	<li><%= link_to 'Hide completed tasks', tasks_path(show_completed: 0) %></li>
  <% else %>
  	<li><%= link_to 'Show completed tasks', tasks_path(show_completed: 1) %></li> 
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<% if @task.errors.any? %>
  There were some errors!
  <ul>
    <% @task.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

<hr />

<ul>
  <li><%= link_to "Back to index", tasks_path %></li>
</ul>

app/views/tasks/show.html.erb
<h3>Task Details</h3>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @task.notes %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date.strftime("%m-%d-%Y") %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<hr />

<ul>
  <li><%= link_to 'Edit this task', edit_task_path(@task) %></li>
  <li><%= link_to "Back to index", tasks_path %></li>
</ul>